# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 16b2915206f06335dab002275712e55dc26d8c30e141954f9f10f55d167f0e9636292bf3b1f269f55c17f6e4cd93dcdea18ef7b9e4841df53de224376e68f859

test:
  secret_key_base: 13211451e8642297e015f8cd4f55db77bb1ab417890540cc831580a37695e40e1d119da42365cee0ff0731b5ac31184e73e5de5eda299697284a95835a4b5708

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
